# Generated by Django 3.1.2 on 2020-11-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20, verbose_name='İsim')),
                ('soyisim', models.CharField(max_length=20, verbose_name='Soyisim')),
                ('numara', models.IntegerField(default=0, unique=True)),
            ],
        ),
    ]
